"""empty message

Revision ID: 5d1061f271e8
Revises: d1ce634d07c4
Create Date: 2019-04-14 01:47:48.827766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1061f271e8'
down_revision = 'd1ce634d07c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('fun', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('roles', 'fun')
    # ### end Alembic commands ###
