"""empty message

Revision ID: bbe5a31f3684
Revises: 5d1061f271e8
Create Date: 2019-04-14 01:52:55.100482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe5a31f3684'
down_revision = '5d1061f271e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'fun')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('roles', sa.Column('fun', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
